= ROSA Fruits Application
:experimental:

A simple REST API that uses https://aws.amazon.com/dynamodb/[AWS DynomoDB] as its data store. The application is intended to demonstrate how to integrate the AWS Native Services from an OpenShift cluster deployed via   https://aws.amazon.com/rosa/[ROSA].

== Pre-Requisites

- AWS Account with permissions to:
 * Create IAM Role
 * Create IAM Policy
 * Create OIDC Provider

- https://aws.amazon.com/cli/[AWS CLI]

- https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.7/[OpenShift Client(oc)]

- https://git-scm.com/[Git]

- https://httpie.io/[HTTPie]

- Java 11

== Download Project Sources

[source,bash]
----
git clone https://github.com/kameshsampath/rosa-fruits-app
export DEMO_HOME="$PWD"
export AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r ".Account")
export OIDC_BUCKET_NAME="rosa-demos-oidc"
export AWS_REGION="us-west-2"
export ROSA_DEMO_ROLE_NAME="$AWS_ACCOUNT-rosa-demos-role"
export ROSA_DEMO_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT:role/$ROSA_DEMO_ROLE_NAME"
----

== ROSA Cluster Setup

[source,bash]
----
rosa create cluster --cluster-name="my-rosa-cluster"
----

The command above will create the ROSA cluster in your default AWS region, type `rosa --help` for more information.

== AWS Preparation

The example will be using custom OIDC provider on AWS to demonstrate the use of ProjectedServiceAccount Token via STS, the following section details on how to setup the same.

- Copy `$DEMO_HOME/setup/env/passwords.example` to `$DEMO_HOME/setup/env/passwords`

- Update the `$DEMO_HOME/setup/env/passwords` with your AWS Access and Secret Keys.

[source,bash]
----
$DEMO_HOME/setup/hack.sh
----

== Packaging and Deploying to OpenShift

The application uses https://www.eclipse.org/jkube/[Eclipse JKube] maven plugin to build and deploy the Java Application to OpenShift.

[source,bash]
----
./mvnw -Daws.role.arn=$ROSA_DEMO_ROLE_ARN \
  -Daws.region=$AWS_REGION clean package
----

== Testing Application

The AWS IAM role allows accessing the application only from `rosa-demos` workspace and as `rosa-demo-sa`,

Get the Route:

[source,bash]
----
export APP_URL=$(oc get route rosa-fruits-app -n rosa-demos)
----

The following REST URI end points are available:

[NOTE,caption=GET Methods]
====
* Lists all fruit

e.g.

[source,bash]
----
http $APP_URL/api/fruit/apple
----

* $APP_URL/api/fruit/{name} - Get a fruit by its `name`

e.g.

[source,bash]
----
http $APP_URL/api/fruit/apple
----

====

[NOTE,caption=POST Methods]
====

* Adds a fruit, takes a JSON payload

[source,json]
----
{
  "name": "apple",
  "season": "fall"
}
----

e.g.

[source,bash]
----
http POST $APP_URL/api/fruit name=apple season=fall
----

====

[NOTE,caption=DELETE Methods]
====
* Delete a fruit by its `name`

e.g.

[source,bash]
----
http DELETE $APP_URL/api/fruit/apple
----
====

== Verify IAM

To make sure the IAM works, try deploying the application a different namespace, for e.g. `demos`

[source,bash]
----
oc new-project demos
./mvnw -Daws.role.arn=$ROSA_DEMO_ROLE_ARN -Daws.region=$AWS_REGION clean package
----

Now when you try any of the API methods above, you should get HTTP 403 as the IAM policy controls the Service Account (`rosa-demo-sa`) and its namespace.

== Development

Start the local DynamoDB server

[source,bash]
----
docker compose up -d $DEMO_HOME/docker-compose.yml
----

Access the local DynamoDB server using http://localhost:8000/shell, and run the following command to create the table:

[source,bash]
----
var params = {
    TableName: 'QuarkusFruits',
    KeySchema: [{ AttributeName: 'fruitName', KeyType: 'HASH' }],
    AttributeDefinitions: [{  AttributeName: 'fruitName', AttributeType: 'S', }],
    ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1, }
};

dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err);
    else ppJson(data);

});
----

Now start Quarkus Application in dev mode 

[source,bash]
----
./mvnw clean compile quarkus:dev
----

== Powered by

This project uses Quarkus, the Supersonic Subatomic Java Framework. If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .
