---
- debug: msg="Jai Guru"

- name: Create AWS Credentials folder
  file:
    path: "/home/runner/.aws"
    state: directory
    mode: 0644

- name: Create AWS Credentials file
  file:
    path: "/home/runner/.aws/credentials"
    state: touch
    mode: 0644

- name: Save AWS Credentials
  copy:
    dest: "{{ansible_env.HOME}}/.aws/credentials"
    content: |
      [default]
      aws_access_key_id     = {{ aws_access_key }}
      aws_secret_access_key = {{ aws_secret_key }}


- include: rollback.yml
  when: rollback

- include: setup.yml
  when: not rollback