---
version: 1

build_arg_defaults:
  ANSIBLE_RUNNER_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.11-devel'

# ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend: |
    RUN dnf -y --nodocs install wget curl tar unzip openssl jq
    RUN cd /tmp
    RUN wget -Oopenshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.7/openshift-client-linux.tar.gz
    RUN tar --exclude='README.md' -C /usr/local/bin  -zxf openshift-client-linux.tar.gz
    RUN wget -Oawscliv2.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    RUN unzip awscliv2.zip
    RUN ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    RUN wget -O/usr/local/bin/rosa https://github.com/openshift/rosa/releases/download/v1.0.2/rosa-linux-amd64
    RUN chmod +x /usr/local/bin/oc /usr/local/bin/kubectl /usr/local/bin/rosa
    RUN dnf -y clean all
  append:
    - RUN oc version
    - RUN kubectl version
    - RUN rosa version
    - RUN aws --version
